export interface Work {
  slug: string;
  title: string;
  year: string;
  medium: string;
  themes: string[];
  description: string;
  longDescription: string;
  image: string;
  orientation: 'vertical' | 'horizontal';
  featured: boolean;
}

export const works: Work[] = [
  {
    slug: 'sdraiati',
    title: 'Sdraiati',
    year: '2023',
    medium: 'Ceramics',
    themes: ['body', 'ritual', 'fragility', 'stillness'],
    description: 'A year-long ritual of making. Three hundred and sixty-five ceramic figures lying down like an intimate diary of suspended time, vulnerability, exhaustion, tenderness, and persistence.',
    longDescription: 'Sdraiati is a durational work spanning an entire year—365 days, 365 ceramic figures, each one shaped by hand in the intimacy of a daily ritual. The figures lie down, embodying states of rest, vulnerability, exhaustion, tenderness, and quiet persistence. Together they form a tactile diary of time passing, a meditation on the body as vessel of accumulated experience. The repetition becomes both discipline and surrender, each small figure a fragment of presence reclaimed from the flux of days.',
    image: new URL('../assets/work-sdraiati.jpeg.asset.json', import.meta.url).toString(),
    orientation: 'vertical',
    featured: true,
  },
  {
    slug: 'contenere',
    title: 'Contenere',
    year: '2022',
    medium: 'Plaster, Installation',
    themes: ['body', 'memory', 'absence', 'transformation'],
    description: 'A vessel-body, holding memory, presence and absence. A form that shelters what continuously changes.',
    longDescription: 'Contenere explores the body as container—a vessel that holds not only physical substance but also memory, emotion, and the invisible residue of experience. The plaster form suggests both protection and exposure, a shelter that reveals what it contains. The work investigates the threshold between holding and releasing, between what remains and what transforms.',
    image: '/src/assets/work-contenere.jpg',
    orientation: 'vertical',
    featured: true,
  },
  {
    slug: 'the-void-that-fills',
    title: 'The Void That Fills / Trivia',
    year: '2021',
    medium: 'Plaster, Sculpture',
    themes: ['body', 'absence', 'memory', 'trace'],
    description: 'A plaster sculpture generated by the negative space of an embrace: the void becomes body, memory becomes form.',
    longDescription: 'The Void That Fills originates from the space between two embracing bodies—the negative space of an intimate gesture cast in plaster. What was empty becomes solid; what was invisible becomes tangible. The sculpture captures the paradox of absence as presence, the void as the most eloquent form. Memory, frozen in the material, becomes a new kind of body—one made entirely of what was between.',
    image: '/src/assets/work-void.jpg',
    orientation: 'vertical',
    featured: true,
  },
  {
    slug: 'how-much-can-a-feeling-weigh',
    title: 'How Much Can a Feeling Weigh?',
    year: '2022',
    medium: 'Ceramics',
    themes: ['body', 'trace', 'transformation', 'fragility'],
    description: 'The trace of a human heart fossilized in ceramic, where emotion acquires weight, surface and permanence.',
    longDescription: 'How Much Can a Feeling Weigh? materializes the intangible. A human heart—the universal symbol of emotion—is rendered in ceramic, fossilized as if excavated from a distant future. The work asks: what happens when we give physical weight to feeling? When emotion acquires surface, texture, permanence? The ceramic heart becomes a relic of inner life, a fossil of the psyche, simultaneously intimate and archaeological.',
    image: '/src/assets/work-feeling.jpg',
    orientation: 'vertical',
    featured: true,
  },
  {
    slug: 'kommatia',
    title: 'Kommátia',
    year: '2020',
    medium: 'Video',
    themes: ['memory', 'unconscious', 'trace', 'transformation'],
    description: 'Fragments, ruins, thresholds. A video work that moves through matter and memory as if entering a psychic landscape.',
    longDescription: 'Kommátia (from the Greek for "fragments") is a video work that navigates through ruins, thresholds, and material traces as if traversing a psychic landscape. The camera moves slowly through spaces that feel simultaneously archaeological and psychological—places where memory has left its mark on stone, plaster, and light. The work collapses the distance between external ruin and internal fragmentation, suggesting that every threshold crossed is also a crossing within.',
    image: '/src/assets/work-kommatia.jpg',
    orientation: 'horizontal',
    featured: true,
  },
  {
    slug: 'who-you-are',
    title: 'Who You Are',
    year: '2021',
    medium: 'Installation, Photography',
    themes: ['unconscious', 'trace', 'body', 'ritual'],
    description: 'Automatic writing and portraiture converge in an installation that reveals the unstable threshold between self-description and the unconscious.',
    longDescription: 'Who You Are brings together automatic writing and photographic portraiture in an installation that questions the stability of self-knowledge. Participants are invited to describe themselves in writing while being photographed—the written text and the captured image rarely align, revealing the gap between how we narrate ourselves and who we appear to be. The work exposes the unconscious as an active force in self-representation, making visible the threshold where identity becomes fluid.',
    image: '/src/assets/work-whoyouare.jpg',
    orientation: 'vertical',
    featured: true,
  },
  {
    slug: 'window',
    title: 'Window',
    year: '2019',
    medium: 'Installation',
    themes: ['absence', 'stillness', 'memory', 'trace'],
    description: 'A liminal space between interior and exterior, a threshold where light becomes memory and absence becomes presence.',
    longDescription: 'Window is an installation that transforms the architectural element of the window into a meditation on thresholds—between interior and exterior, presence and absence, memory and the present moment. Light enters the space as both illumination and metaphor, casting shadows that suggest what is no longer there. The work invites contemplation of the in-between, the liminal space where seeing and remembering converge.',
    image: '/src/assets/work-window.jpg',
    orientation: 'vertical',
    featured: false,
  },
  {
    slug: 'we-are-still-flying',
    title: 'We Are Still Flying',
    year: '2023',
    medium: 'Installation',
    themes: ['body', 'fragility', 'transformation', 'stillness'],
    description: 'Suspended elements suggesting flight, fragility, and the persistence of hope in the face of gravity.',
    longDescription: 'We Are Still Flying is an installation of suspended forms that hover in gallery space, defying gravity through material lightness and spatial arrangement. The work speaks to the human capacity for transcendence—physical, emotional, spiritual—even in conditions of fragility and constraint. The suspended elements, ethereal and barely there, embody a state of perpetual becoming, a flight that never lands, a hope that persists against the pull of the earth.',
    image: '/src/assets/work-flying.jpg',
    orientation: 'horizontal',
    featured: false,
  },
];

export const exhibitions = [
  { year: '2023', title: 'Sdraiati — Solo Exhibition', venue: 'Galleria d\'Arte Contemporanea', location: 'Milan, Italy' },
  { year: '2023', title: 'We Are Still Flying', venue: 'Kunsthalle', location: 'Berlin, Germany' },
  { year: '2022', title: 'Contenere — Solo Exhibition', venue: 'Centre d\'Art', location: 'Paris, France' },
  { year: '2022', title: 'How Much Can a Feeling Weigh?', venue: 'MACRO Museum', location: 'Rome, Italy' },
  { year: '2021', title: 'The Void That Fills / Trivia', venue: 'Fondazione Arte', location: 'Turin, Italy' },
  { year: '2021', title: 'Who You Are', venue: 'Palazzo delle Esposizioni', location: 'Rome, Italy' },
  { year: '2020', title: 'Kommátia', venue: 'Biennale Giovani', location: 'Venice, Italy' },
  { year: '2019', title: 'Window', venue: 'Galerie Contemporaine', location: 'Lyon, France' },
];

export const awards = [
  { year: '2023', title: 'Premio Arte Emergente', institution: 'Fondazione Italiana per l\'Arte Contemporanea' },
  { year: '2022', title: 'Residency Award', institution: 'Cité Internationale des Arts, Paris' },
  { year: '2021', title: 'Young Artists Prize', institution: 'MAXXI Museum, Rome' },
  { year: '2020', title: 'Biennale Giovani Selection', institution: 'Venice Biennale Foundation' },
];

export const themes = ['body', 'unconscious', 'ritual', 'memory', 'absence', 'trace', 'fragility', 'stillness', 'transformation'] as const;
export const mediums = ['Ceramics', 'Plaster', 'Plaster, Sculpture', 'Plaster, Installation', 'Installation', 'Installation, Photography', 'Video'] as const;
